gpt-4-0613:
    import: "./my-chat.yaml"
    parameters:
        name: "gpt-4-0613"
        body:
            model: "gpt-4-0613"
            max_tokens: 512

gpt-3.5-turbo-0613:
    import: "./my-chat.yaml"
    parameters:
        name: "gpt-3.5-turbo-0613"
        body:
            model: "gpt-3.5-turbo-0613"
            max_tokens: 512

my-chat:
    import: "./my-chat.yaml"
    parameters:
        name: "my-chat"

text-davinci-003:
    import: "./openai-text.yaml"
    parameters:
        name: "text-davinci-003"
        body:
            model: "text-davinci-003"
            max_tokens: 512

text-davinci-002:
    import: "./openai-text.yaml"
    parameters:
        name: "text-davinci-002"
        body:
            model: "text-davinci-002"
            max_tokens: 512

my-sdk:
    import: "./my-sdk.yaml"
    parameters:
        name: "my-sdk"
